steps:
  # Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/diagnostic-pro-mvp/diagnosticpro-frontend:latest', '.']
  
  # Push to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/diagnostic-pro-mvp/diagnosticpro-frontend:latest']
  
  # Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args: 
      - 'run'
      - 'deploy'
      - 'diagnosticpro-frontend'
      - '--image'
      - 'gcr.io/diagnostic-pro-mvp/diagnosticpro-frontend:latest'
      - '--region'
      - 'us-east5'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--port'
      - '3000'
      - '--memory'
      - '1Gi'
      - '--cpu'
      - '1'
      - '--max-instances'
      - '10'

images:
  - 'gcr.io/diagnostic-pro-mvp/diagnosticpro-frontend:latest'